Update zshrc

diff --git a/dotfiles/macos/zshrc b/dotfiles/macos/zshrc
--- a/dotfiles/macos/zshrc
+++ b/dotfiles/macos/zshrc
@@ -119,7 +119,22 @@ alias profilezsh='zshrcProfile() { export ZSH_PROFILE=true; exec zsh }; zshrcPro
 
 # Functions
 transfer(){ if [ $# -eq 0 ];then echo "No arguments specified.\nUsage:\n transfer <file|directory>\n ... | transfer <file_name>">&2;return 1;fi;if tty -s;then file="$1";file_name=$(basename "$file");if [ ! -e "$file" ];then echo "$file: No such file or directory">&2;return 1;fi;if [ -d "$file" ];then file_name="$file_name.zip" ,;(cd "$file"&&zip -r -q - .)|curl --progress-bar --upload-file "-" "https://transfer.sh/$file_name"|tee /dev/null,;else cat "$file"|curl --progress-bar --upload-file "-" "https://transfer.sh/$file_name"|tee /dev/null;fi;else file_name=$1;curl --progress-bar --upload-file "-" "https://transfer.sh/$file_name"|tee /dev/null;fi;}
-update_zshrc(){if [[ "$(cat $HOME/.zshrc | md5)" != "$(curl -s https://raw.githubusercontent.com/Im-Fran/Im-Fran/main/dotfiles/macos/zshrc | md5)" ]]; then curl -s https://raw.githubusercontent.com/Im-Fran/Im-Fran/main/dotfiles/macos/zshrc > "$HOME/.zshrc";fi}
+update_zshrc() {
+    if ! nc -zw1 google.com 443; then
+        echo "Error: No network connection available."
+        return 1
+    fi
+
+    local local_md5 remote_md5
+
+    local_md5=$(md5sum "$HOME/.zshrc" | awk '{print $1}')
+    remote_md5=$(curl -s https://raw.githubusercontent.com/Im-Fran/Im-Fran/main/dotfiles/macos/zshrc | md5sum | awk '{print $1}')
+
+    if [[ "$local_md5" != "$remote_md5" ]]; then
+        curl -s https://raw.githubusercontent.com/Im-Fran/Im-Fran/main/dotfiles/macos/zshrc > "$HOME/.zshrc"
+    fi
+}
+
 update_zshrc &!
 
 
