Update zshrc

diff --git a/dotfiles/macos/zshrc b/dotfiles/macos/zshrc
--- a/dotfiles/macos/zshrc
+++ b/dotfiles/macos/zshrc
@@ -144,20 +144,43 @@ alias run-script='runscript'
 alias profilezsh='zshrcProfile() { export ZSH_PROFILE=true; exec zsh }; zshrcProfile'
 
 # Functions
-transfer(){ if [ $# -eq 0 ];then echo "No arguments specified.\nUsage:\n transfer <file|directory>\n ... | transfer <file_name>">&2;return 1;fi;if tty -s;then file="$1";file_name=$(basename "$file");if [ ! -e "$file" ];then echo "$file: No such file or directory">&2;return 1;fi;if [ -d "$file" ];then file_name="$file_name.zip" ,;(cd "$file"&&zip -r -q - .)|curl --progress-bar --upload-file "-" "https://transfer.sh/$file_name"|tee /dev/null,;else cat "$file"|curl --progress-bar --upload-file "-" "https://transfer.sh/$file_name"|tee /dev/null;fi;else file_name=$1;curl --progress-bar --upload-file "-" "https://transfer.sh/$file_name"|tee /dev/null;fi;}
 update_zshrc() {
+    # Check if there is an internet connection before proceeding
     if ! nc -zw1 google.com 443 >/dev/null 2>&1; then
         echo "Error: No network connection available. Stopping ZSHRC Update." >&2
         return 1
     fi
 
-    local local_md5 remote_md5
+    # Define the URL for the remote .zshrc content
+    local url="https://raw.githubusercontent.com/Im-Fran/Im-Fran/main/dotfiles/macos/zshrc"
+    
+    # Fetch the remote content and store it in a variable
+    local remote_zshrc_content
+    remote_zshrc_content=$(curl -s -w "%{http_code}" -o /tmp/zshrc_temp "$url")
+    
+    # Extract the HTTP status code from the curl response
+    local http_status="${remote_zshrc_content: -3}"
 
-    local_md5=$(cat "$HOME/.zshrc" | md5)
-    remote_md5=$(curl -fsSL https://raw.githubusercontent.com/Im-Fran/Im-Fran/main/dotfiles/macos/zshrc | md5)
+    # Check if the HTTP status is 200 (OK)
+    if [[ "$http_status" -eq 200 ]]; then
+        # Read the local .zshrc file's MD5 hash
+        local local_md5 remote_md5
+        local_md5=$(md5 -q "$HOME/.zshrc")
 
-    if [[ "$local_md5" != "$remote_md5" ]]; then
-        curl -s https://raw.githubusercontent.com/Im-Fran/Im-Fran/main/dotfiles/macos/zshrc > "$HOME/.zshrc"
+        # Calculate the MD5 hash of the fetched remote content
+        remote_md5=$(echo "$remote_zshrc_content" | head -n -3 | md5 -q)
+
+        # If the hashes are different, replace the local .zshrc with the remote content
+        if [[ "$local_md5" != "$remote_md5" ]]; then
+            echo "$remote_zshrc_content" > "$HOME/.zshrc"
+            echo "Updated .zshrc file successfully."
+        else
+            echo ".zshrc is already up to date."
+        fi
+    else
+        # If the response was not 200, display an error message
+        echo "Failed to fetch the remote .zshrc. HTTP Status: $http_status" >&2
+        return 1
     fi
 }
 
