patch: update run_script to use API

diff --git a/dotfiles/macos/zshrc b/dotfiles/macos/zshrc
--- a/dotfiles/macos/zshrc
+++ b/dotfiles/macos/zshrc
@@ -5,6 +5,13 @@ if [[ -n "$ZSH_PROFILE" ]]; then
   zmodload zsh/zprof
 fi
 
+# Verify Internet Connection
+if ping -c 1 -W 1 1.1.1.1 >/dev/null 2>&1 || ping -c 1 -W 1 8.8.8.8 >/dev/null 2>&1; then
+    export HAS_CONNECTION=true
+else
+    export HAS_CONNECTION=false
+fi
+
 # Load environment variables
 if [ -f "$HOME/.env" ]; then
     source $HOME/.env
@@ -86,53 +93,66 @@ runscript () {
     fi
 
     local script_name="$1"
-    local script_url="https://github.com/Im-Fran/Im-Fran/raw/main/dotfiles/scripts/${script_name}"
+    local script_url="https://api.github.com/repos/Im-Fran/Im-Fran/contents/dotfiles/scripts/${script_name}"
     local cache_dir="$HOME/.cache/runscript"
     local local_script="$cache_dir/$script_name"
 
     mkdir -p "$cache_dir"
 
-    # Function to calculate MD5 hash
-    calculate_md5() {
-        if command -v md5sum &> /dev/null; then
-            md5sum | awk '{print $1}'
-        elif command -v md5 &> /dev/null; then
-            md5
-        else
-            echo "Error: No MD5 utility available."
-            return 1
-        fi
-    }
+    if [ "$HAS_CONNECTION" == "false" && -f "$local_script" ]; then
+        echo "There's no internet connection to check for updates. Using local script..."
+        chmod +x "$local_script" # Ensure script is executable
 
-    # Check and update the script if needed
-    if [ -f "$local_script" ]; then
-        echo "Checking for updates to $script_name..."
-        # Fetch remote script MD5
-        remote_md5=$(curl -fsSL -H "Cache-Control: no-cache" "$script_url" | calculate_md5)
-        if [ $? -ne 0 ]; then
-            echo "Error: Failed to fetch remote script MD5."
-            return 1
-        fi
-
-        # Calculate local script MD5
-        local_md5=$(cat "$local_script" | calculate_md5)
-        if [ "$remote_md5" != "$local_md5" ]; then
-            echo "Updating script: $script_name"
-            curl -fsSL -H "Cache-Control: no-cache" "$script_url" -o "$local_script" || { echo "Error: Failed to update the script."; return 1; }
-        else
-            echo "Script $script_name is up to date."
-        fi
+        shift
+        zsh "$local_script" "$@"
+    elif [ "$HAS_CONNECTION" == "false" && ! -f "$localscript" ]
+        echo "There's no internet connection and couldn't find a local copy of the script."
+        return 1
     else
-        echo "Downloading script: $script_name"
-        curl -fsSL -H "Cache-Control: no-cache" "$script_url" -o "$local_script" || { echo "Error: Failed to fetch the script."; return 1; }
+        # Function to calculate MD5 hash
+        calculate_md5() {
+            if command -v md5sum &> /dev/null; then
+                md5sum | awk '{print $1}'
+            elif command -v md5 &> /dev/null; then
+                md5
+            else
+                echo "Error: No MD5 utility available."
+                return 1
+            fi
+        }
+
+        remote_script_content=$(curl -fsSL $script_url --header "Authorization: Bearer $GITHUB_TOKEN" --header "X-GitHub-Api-Version: 2022-11-28" --header "Cache-Control: no-cache" | jq -r .content | base64 --decode)
+
+        # Check and update the script if needed
+        if [ -f "$local_script" ]; then
+            echo "Checking for updates to $script_name..."
+            # Fetch remote script MD5
+            remote_md5=$(curl -fsSL -H "Cache-Control: no-cache" "$script_url" | calculate_md5)
+            if [ $? -ne 0 ]; then
+                echo "Error: Failed to fetch remote script MD5."
+                return 1
+            fi
+
+            # Calculate local script MD5
+            local_md5=$(cat "$local_script" | calculate_md5)
+            if [ "$remote_md5" != "$local_md5" ]; then
+                echo "Updating script: $script_name"
+                curl -fsSL -H "Cache-Control: no-cache" "$script_url" -o "$local_script" || { echo "Error: Failed to update the script."; return 1; }
+            else
+                echo "Script $script_name is up to date."
+            fi
+        else
+            echo "Downloading script: $script_name"
+            curl -fsSL -H "Cache-Control: no-cache" "$script_url" -o "$local_script" || { echo "Error: Failed to fetch the script."; return 1; }
+        fi
+
+        # Ensure the script is executable
+        chmod +x "$local_script"
+
+        # Execute the script
+        shift
+        zsh "$local_script" "$@"
     fi
-
-    # Ensure the script is executable
-    chmod +x "$local_script"
-
-    # Execute the script
-    shift
-    zsh "$local_script" "$@"
 }
 
 
