Update zshrc

diff --git a/dotfiles/ubuntu/zshrc b/dotfiles/ubuntu/zshrc
--- a/dotfiles/ubuntu/zshrc
+++ b/dotfiles/ubuntu/zshrc
@@ -135,8 +135,8 @@ alias run-script='runscript'
 # Functions
 transfer(){ if [ $# -eq 0 ];then echo "No arguments specified.\nUsage:\n transfer <file|directory>\n ... | transfer <file_name>">&2;return 1;fi;if tty -s;then file="$1";file_name=$(basename "$file");if [ ! -e "$file" ];then echo "$file: No such file or directory">&2;return 1;fi;if [ -d "$file" ];then file_name="$file_name.zip" ,;(cd "$file"&&zip -r -q - .)|curl --progress-bar --upload-file "-" "https://transfer.sh/$file_name"|tee /dev/null,;else cat "$file"|curl --progress-bar --upload-file "-" "https://transfer.sh/$file_name"|tee /dev/null;fi;else file_name=$1;curl --progress-bar --upload-file "-" "https://transfer.sh/$file_name"|tee /dev/null;fi;}
 update_zshrc() {
-    if ! nc -zw1 google.com 443; then
-        echo "Error: No network connection available."
+    if ! nc -zw1 google.com 443 >/dev/null 2>&1; then
+        echo "Error: No network connection available. Stopping ZSHRC Update." >&2
         return 1
     fi
 
@@ -149,6 +149,7 @@ update_zshrc() {
         curl -s https://raw.githubusercontent.com/Im-Fran/Im-Fran/main/dotfiles/ubuntu/zshrc > "$HOME/.zshrc"
     fi
 }
+
 
 update_zshrc &!
 
